apiVersion: mail.circa10a.github.io/v1alpha1
kind: Mail
metadata:
  labels:
    app.kubernetes.io/name: postk8s
    app.kubernetes.io/managed-by: kustomize
  name: mail-sample
spec:
  service: test
  from:
    name: "Sender Name"
    organization: "Acme Sender"
    address1: "123 Sender St"
    address2: "Suite 100"
    city: "Senderville"
    state: "CA"
    postcode: "94016"
    country: "US"
  to:
    name: "Recipient Name"
    organization: "Acme Recipient"
    address1: "456 Recipient Ave"
    address2: "Apt 4B"
    city: "Receivertown"
    state: "NY"
    postcode: "10001"
    country: "US"